"""Prompt templates for MapCoder reproduction (paper Appendix B)."""
from .mapcoder_prompts import (
    RETRIEVAL_SYSTEM,
    RETRIEVAL_USER_TEMPLATE,
    PLAN_GEN_SYSTEM,
    PLAN_GEN_TEMPLATE,
    CONFIDENCE_SYSTEM,
    CONFIDENCE_TEMPLATE,
    CODING_SYSTEM,
    CODING_TEMPLATE,
    DEBUG_SYSTEM,
    DEBUG_TEMPLATE,
)

__all__ = [
    "RETRIEVAL_SYSTEM",
    "RETRIEVAL_USER_TEMPLATE",
    "PLAN_GEN_SYSTEM",
    "PLAN_GEN_TEMPLATE",
    "CONFIDENCE_SYSTEM",
    "CONFIDENCE_TEMPLATE",
    "CODING_SYSTEM",
    "CODING_TEMPLATE",
    "DEBUG_SYSTEM",
    "DEBUG_TEMPLATE",
]
